config/routes.rb
Rails.application.routes.draw do

  resources :categories
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'static#home'
  get '/asdf', to: 'static#asdf'
  get '/zxcv', to: 'static#zxcv'
  get '/qwer', to: 'static#qwer'

  get '/about', to: 'static#about'
  get '/flatiron', to: 'static#flatiron'
	get '/blog', to: 'posts#index'
	get '/tek', to: 'refs#tek'
 

	get '/export_bookmarks_csv', to: 'bookmarks#export_csv'

	# get 'scrape_bookmarks', to: 'ref#scrape_bookmarks'

	# get 'reload_books', to: 'ref#reload_books'

  resources :posts, :refs, :projects, :tags, :bookmarks, :books
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :books
	has_many :bookmarks
	has_many :tags
	has_many :posts
	has_many :refs
 
	 
	def self.tek_only
		non_tek = ["_ntwk", "_accts", 
		"trilogy", "misc", "port", "_//", "//", "_career", "_hku", 
		"_job", "_learn-videos", "Aida", "bands", "cirque", 
		"flatiron", "glasses", "listen", "mainstage", "Network", "recruiter", 
		"technical-coach", "wework",
		"videos",
		"_mentors",
		"Listen"
	]
		@tek_categories = []
		Category.all.each do |c|
			@tek_categories.push(c) unless non_tek.include?(c.name)
		end
		@tek_categories.sort {|c| c.name.downcase<=>c.name.downcase}
	end
end

app/helpers/refs_helper.rb
module RefsHelper
	def sort_link(column, title = nil)
		title ||= column.titleize
		direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
		icon = sort_direction == "asc" ? "glyphicon glyphicon-chevron-up" : "glyphicon glyphicon-chevron-down"
		icon = column == sort_column ? icon : ""
		link_to "#{title} <span class='#{icon}'></span>".html_safe, {column: column, direction: direction}
	end
end
 

app/views/refs/_images.html.erb
<% @images.each do |img| %>
	<ul>
	<li>public_id: <%= img["public_id"] %></li>
	<li>format: <%= img["format"] %></li>
	<li>created_at: <%= img["created_at"] %></li>
	<li>width: <%= img["width"] %></li>
	<li>height: <%= img["height"] %></li>
	<li>url: <%= link_to 'show_image', img["url"] %></li>
	<li>secure_url: <%= link_to 'show_image', img["secure_url"] %></li>
	<hr />
	</ul>
	<% end %>
<hr />
 

app/views/refs/_pdfs.html.erb
<% @pdfs.each do |pdf| %>
	<hr />
	<ul>
		<li>public_id: <%= pdf["public_id"] %></li>
		<li>format: <%= pdf["format"] %></li>
		<li>url: <%= link_to 'show_pdf', pdf["url"] %></li>
		<li>secure_url: <%= link_to 'show_pdf', pdf["secure_url"] %></li>
	</ul>
	<% end %>
<hr />
 

app/views/refs/_refs_sidebar.html.erb
<%= link_to "Groups", groups_path %> | 
<%= link_to "Topics", topics_path %> |
<%= link_to "New Ref", new_ref_path %> 
<hr>
<h3><h3>mentors:</h3>
<% mentors.each do |mentor|%>
  <%= link_to mentor.name, mentor.url %><br>
<% end %>
<hr>
<h3>videos</h3>
<% videos.each do |video|%>
  <%= link_to video.name, video.url %><br>
<% end %>
<hr>
<h3>books</h3>
<% books.each do |book|%>
  <%= link_to book.name, book.url %><br>
<% end %>
<hr>
<h3>bookmarks</h3>
<% bookmarks.each do |bookmark|%>
  <%= link_to bookmark.name, bookmark.url %><br>
<% end %>
<hr>
<h3>docs</h3>
<% docs.each do |doc|%>
  <%= link_to doc.name, doc.url %><br>
<% end %>
<hr>
<h3>Pdfs</h3>
<% pdfs.each do |pdf|%>`
  <%= link_to pdf.name, pdf.url %><br>
<% end %></h3>
<h3>

app/views/refs/edit.html.erb
<div class="wrapper wrapper_padding clearfix">
<div class="sidebar"></div>
  <div class="col-0">
    <h4>Edit Reference</h4>
    <hr>
      <p>
      <%= form_for @ref do |f| %>
      <p>
        <%= f.label :name %>
        <%= f.text_field :name %><br>
      </p>
      <p>
        <%= f.label :format %>
        <%= f.text_field :format %><br>
      </p>
      <p>
        <%= f.label :url %>
        <%= f.text_field :url %><br>
      </p>
      <p>
        <%= f.label :content %>
        <%= f.text_area :content %><br>
      </p>
      <p>
        <%= f.label :topic %>
        <%= f.collection_select :id, Topic.all, :id, :name %>
      </p>
        <%= f.submit %>
      <% end %>
    </p>
  </div>
</div>

app/views/refs/index.html.erb
<h1>Refs</h1> 
<%= stylesheet_link_tag    '//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js', 'data-turbolinks-track' => true %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

<div class="container">
	<table>
		<thead>
			<tr>
				<th><%= sort_link "format" %></th> 
				<th><%= sort_link "category" %></th> 
				<th><%= sort_link "title" %></th>
			</tr>
		</thead>
		<tbody>
			<% @refs.each do |ref| %>
				<tr>
					<td><%= ref.format %></td>
					<td><%= ref.category %></td>
					<% if ref.format === 'pdf' %>
						<td><%= link_to ref.title, ref_path(ref) %></td>
					<% else %>
						<td><%= link_to ref.title, ref.url %></td>
					<% end %>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/refs/new.html.erb
<div class="wrapper wrapper_padding clearfix">
<div class="sidebar"></div>
  <div class="col-0">
    <h4>New Reference</h4>
    <%= form_for @ref do |f| %>
    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name, size: 30 %><br>
    </p>
    <p>
      <%= f.label :format %><br>
      <%= f.text_field :format, size: 30 %><br>
    </p>
    <p>
      <%= f.label :url %><br>
      <%= f.text_field :url, size: 30 %><br>
    </p>
    <p>
      <%= f.label :content %><br>
      <%= f.text_area :content, cols: 30, rows: 5 %><br>
    </p>
    <p>
      <%= f.label :posts %><br>
      <%= f.collection_select :post_ids, Post.all, :id, :title %>
    </p>
      <%= f.submit %>
    <% end %>
    </p>
  </div>
</div>

app/views/refs/show.html.erb
 
<div>
 <h2> hello </h2>

	<% if @ref.format === 'pdf' %>
		<p><%= link_to @ref.title, @ref.url %></p>	
	<% elsif @ref.format === 'bookmark' %>
		<p><%= @ref.title %>  | <%= @ref.title %> </p>
	<% else %>
<% end %>
</div>