config/routes.rb
Rails.application.routes.draw do

  resources :categories
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'static#home'
  get '/asdf', to: 'static#asdf'
  get '/zxcv', to: 'static#zxcv'
  get '/qwer', to: 'static#qwer'

  get '/about', to: 'static#about'
  get '/flatiron', to: 'static#flatiron'
	get '/blog', to: 'posts#index'
	get '/tek', to: 'refs#tek'
 

	get '/export_bookmarks_csv', to: 'bookmarks#export_csv'

	# get 'scrape_bookmarks', to: 'ref#scrape_bookmarks'

	# get 'reload_books', to: 'ref#reload_books'

  resources :posts, :refs, :projects, :tags, :bookmarks, :books
end

app/views/layouts/_card.html.erb
<img src="http://res.cloudinary.com/smithwebtek/image/upload/c_scale,w_1363/v1516389815/DSC00071_vjo8te.jpg" width="150px"
  height="150px" style="border-radius: 5px" alt="bradsmith" class="sidebar-blog responsive">

<br />
<br />
<h3>Brad Smith</h3>
<h6>Full Stack Web Developer</h6>
<br />
<hr />
<h6>Ruby, jQuery, JavaScript</h6>
<h6>Ruby on Rails</h6>
<h6>React - Redux</h6>
<h6>Database Design</h6>
<h6>Website Design</h6>
<br />
<br />
<h4>
<%= link_to "Download Resume", asset_path('resume.pdf') %>
</h4>

app/views/layouts/_contact.html.erb
<a href="https://github.com/smithwebtek" target="_blank">
  <i class="fa fa-github fa-1x" aria-hidden="true" style="margin: 3px"></i>
</a>
<a href="https://linkedin.com/in/smithwebtek" target="_blank">
  <i class="fa fa-linkedin fa-1x" aria-hidden="true" style="margin: 3px"></i>
</a>
<a href="mailto:brad@smithWEBtek.com">
  <i class="fa fa-envelope fa-1x" aria-hidden="true" style="margin: 3px"></i>
</a>
<a href="https://twitter.com/smithwebtek" target="_blank">
  <i class="fa fa-twitter fa-1x" aria-hidden="true" style="margin: 3px"></i>
</a>

app/views/layouts/_footer.html.erb
<div style="clear: both; margin: 5%">
  <hr>
	<p class="copyright">&copy;2018 smithWEBtek</p>
	<%= render partial: 'layouts/contact' %>
</div>

app/views/layouts/_main_nav.html.erb
<header id="main_nav" class="clearfix col-1">
  <div>
    <h3>
      <a href="<%= root_path %>">smithWEBtek</a>
    </h3>
  </div>
  <div id="flash-messages" class="flash_style">
    <div class="notice">
      <%= notice %>
    </div>
    <div class="alert">
      <%= alert %>
    </div>
	</div>
	<div>
		<nav>
			<%= link_to "about", about_path %>
			|
			<%= link_to "blog", post_path(Post.last.id) %>
			|
			<%= link_to "projects", project_path(Project.last.id) %>
			|
			<%= link_to "tekmarks", bookmarks_path %>
			</div>
		</nav>
  </div>
</header>

app/views/layouts/_main_nav.html1.erb
<header id="main_nav" class="clearfix col-1">
  <div>
    <h3>
      <a href="<%= root_path %>">smithWEBtek</a>
    </h3>
  </div>
  <div id="flash-messages" class="flash_style">
    <div class="notice">
      <%= notice %>
    </div>
    <div class="alert">
      <%= alert %>
    </div>
	</div>
	<div>
		<nav>
			<%= link_to "about", about_path %>
			|
			<%= link_to "blog", post_path(Post.last.id) %>
			|
			<%= link_to "projects", project_path(Project.last.id) %>
			|
			<%= link_to "bookmarks", bookmarks_path %>
			|
			<%#= link_to "admin", new_admin_user_session_path %>
			|
			<% if !current_user %>
				<%= link_to "sign up", new_user_registration_path %>
				|
			<%#= link_to "login",  new_user_session_path %><br>
			<% end %>
 
			<% if current_user && user_signed_in? %>
			<%= link_to "sign out", destroy_user_session_path %>
			|
			<%= link_to "User Account", user_path(current_user) %>

			<div class="flash_style">
				<%= current_user.username.upcase %>, logged in as:
				<%= current_user.role.upcase %>
				user.
				<% end %>
			</div>
		</nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
<head>
  <title>smithWEBtek</title>
  <link href="https://fonts.googleapis.com/css?family=Raleway:400,700" rel="stylesheet">
  <link href="https://use.fontawesome.com/releases/v5.0.4/css/all.css" rel="stylesheet">

  <script src="https://use.fontawesome.com/b7b038f8df.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <%= csrf_meta_tags %>
</head>

<body>
	<%= render partial: 'layouts/main_nav' %>
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>

    <%= yield %>
</body>

<%= render partial: 'layouts/footer' %>

</html>